name: Firebase function deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install npm packages
      run: |
        #cd functions
        #npm install
        
    - name:  Use Package 
      uses: w9jds/firebase-action@master
      with:
          args: use default
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    - name:  Deploy to Firebase 
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only hosting
          #args: deploy --only functions
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
